// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PXVMETA_PXVMETA_H_
#define FLATBUFFERS_GENERATED_PXVMETA_PXVMETA_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace pxvmeta {

struct FontMeta;
struct FontMetaBuilder;

struct PXVMeta;
struct PXVMetaBuilder;

struct FontMeta FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FontMetaBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FONT = 4,
    VT_DISPLAYFONTNAME = 6
  };
  const ::flatbuffers::String *font() const {
    return GetPointer<const ::flatbuffers::String *>(VT_FONT);
  }
  const ::flatbuffers::String *displayFontName() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DISPLAYFONTNAME);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_FONT) &&
           verifier.VerifyString(font()) &&
           VerifyOffset(verifier, VT_DISPLAYFONTNAME) &&
           verifier.VerifyString(displayFontName()) &&
           verifier.EndTable();
  }
};

struct FontMetaBuilder {
  typedef FontMeta Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_font(::flatbuffers::Offset<::flatbuffers::String> font) {
    fbb_.AddOffset(FontMeta::VT_FONT, font);
  }
  void add_displayFontName(::flatbuffers::Offset<::flatbuffers::String> displayFontName) {
    fbb_.AddOffset(FontMeta::VT_DISPLAYFONTNAME, displayFontName);
  }
  explicit FontMetaBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<FontMeta> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<FontMeta>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<FontMeta> CreateFontMeta(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> font = 0,
    ::flatbuffers::Offset<::flatbuffers::String> displayFontName = 0) {
  FontMetaBuilder builder_(_fbb);
  builder_.add_displayFontName(displayFontName);
  builder_.add_font(font);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<FontMeta> CreateFontMetaDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *font = nullptr,
    const char *displayFontName = nullptr) {
  auto font__ = font ? _fbb.CreateString(font) : 0;
  auto displayFontName__ = displayFontName ? _fbb.CreateString(displayFontName) : 0;
  return pxvmeta::CreateFontMeta(
      _fbb,
      font__,
      displayFontName__);
}

struct PXVMeta FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PXVMetaBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VIDEOSEGMENTVIDXES = 4,
    VT_FONTMETAVEC = 6,
    VT_TIMELAPSEV2ENABLED = 8,
    VT_VIDEOSEGMENTVIDXESV2 = 10
  };
  const ::flatbuffers::Vector<int64_t> *videoSegmentVidxes() const {
    return GetPointer<const ::flatbuffers::Vector<int64_t> *>(VT_VIDEOSEGMENTVIDXES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<pxvmeta::FontMeta>> *fontMetaVec() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<pxvmeta::FontMeta>> *>(VT_FONTMETAVEC);
  }
  bool timelapseV2Enabled() const {
    return GetField<uint8_t>(VT_TIMELAPSEV2ENABLED, 1) != 0;
  }
  const ::flatbuffers::Vector<int64_t> *videoSegmentVidxesV2() const {
    return GetPointer<const ::flatbuffers::Vector<int64_t> *>(VT_VIDEOSEGMENTVIDXESV2);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VIDEOSEGMENTVIDXES) &&
           verifier.VerifyVector(videoSegmentVidxes()) &&
           VerifyOffset(verifier, VT_FONTMETAVEC) &&
           verifier.VerifyVector(fontMetaVec()) &&
           verifier.VerifyVectorOfTables(fontMetaVec()) &&
           VerifyField<uint8_t>(verifier, VT_TIMELAPSEV2ENABLED, 1) &&
           VerifyOffset(verifier, VT_VIDEOSEGMENTVIDXESV2) &&
           verifier.VerifyVector(videoSegmentVidxesV2()) &&
           verifier.EndTable();
  }
};

struct PXVMetaBuilder {
  typedef PXVMeta Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_videoSegmentVidxes(::flatbuffers::Offset<::flatbuffers::Vector<int64_t>> videoSegmentVidxes) {
    fbb_.AddOffset(PXVMeta::VT_VIDEOSEGMENTVIDXES, videoSegmentVidxes);
  }
  void add_fontMetaVec(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<pxvmeta::FontMeta>>> fontMetaVec) {
    fbb_.AddOffset(PXVMeta::VT_FONTMETAVEC, fontMetaVec);
  }
  void add_timelapseV2Enabled(bool timelapseV2Enabled) {
    fbb_.AddElement<uint8_t>(PXVMeta::VT_TIMELAPSEV2ENABLED, static_cast<uint8_t>(timelapseV2Enabled), 1);
  }
  void add_videoSegmentVidxesV2(::flatbuffers::Offset<::flatbuffers::Vector<int64_t>> videoSegmentVidxesV2) {
    fbb_.AddOffset(PXVMeta::VT_VIDEOSEGMENTVIDXESV2, videoSegmentVidxesV2);
  }
  explicit PXVMetaBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PXVMeta> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PXVMeta>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PXVMeta> CreatePXVMeta(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<int64_t>> videoSegmentVidxes = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<pxvmeta::FontMeta>>> fontMetaVec = 0,
    bool timelapseV2Enabled = true,
    ::flatbuffers::Offset<::flatbuffers::Vector<int64_t>> videoSegmentVidxesV2 = 0) {
  PXVMetaBuilder builder_(_fbb);
  builder_.add_videoSegmentVidxesV2(videoSegmentVidxesV2);
  builder_.add_fontMetaVec(fontMetaVec);
  builder_.add_videoSegmentVidxes(videoSegmentVidxes);
  builder_.add_timelapseV2Enabled(timelapseV2Enabled);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<PXVMeta> CreatePXVMetaDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<int64_t> *videoSegmentVidxes = nullptr,
    const std::vector<::flatbuffers::Offset<pxvmeta::FontMeta>> *fontMetaVec = nullptr,
    bool timelapseV2Enabled = true,
    const std::vector<int64_t> *videoSegmentVidxesV2 = nullptr) {
  auto videoSegmentVidxes__ = videoSegmentVidxes ? _fbb.CreateVector<int64_t>(*videoSegmentVidxes) : 0;
  auto fontMetaVec__ = fontMetaVec ? _fbb.CreateVector<::flatbuffers::Offset<pxvmeta::FontMeta>>(*fontMetaVec) : 0;
  auto videoSegmentVidxesV2__ = videoSegmentVidxesV2 ? _fbb.CreateVector<int64_t>(*videoSegmentVidxesV2) : 0;
  return pxvmeta::CreatePXVMeta(
      _fbb,
      videoSegmentVidxes__,
      fontMetaVec__,
      timelapseV2Enabled,
      videoSegmentVidxesV2__);
}

inline const pxvmeta::PXVMeta *GetPXVMeta(const void *buf) {
  return ::flatbuffers::GetRoot<pxvmeta::PXVMeta>(buf);
}

inline const pxvmeta::PXVMeta *GetSizePrefixedPXVMeta(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<pxvmeta::PXVMeta>(buf);
}

inline bool VerifyPXVMetaBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<pxvmeta::PXVMeta>(nullptr);
}

inline bool VerifySizePrefixedPXVMetaBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<pxvmeta::PXVMeta>(nullptr);
}

inline void FinishPXVMetaBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<pxvmeta::PXVMeta> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedPXVMetaBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<pxvmeta::PXVMeta> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace pxvmeta

#endif  // FLATBUFFERS_GENERATED_PXVMETA_PXVMETA_H_
